### ISSUE TITLE
add twitter provider

### ISSUE THREAD

**Issue by ihor-bobyr** [dmytro-parfenov/ngx-social-auth#4]
It would be great if you could implement ability to login with twitter, by adding twitter as one of the available providers.
You can read about twitter login flow here.

https://developer.twitter.com/en/docs/authentication/guides/log-in-with-twitter

**Comment by dmytro-parfenov** [comment]
@ihor-bobyr Unfortunately log in with twitter doesn't work without server due CORS policy. But I position my project as a client side library without additional server side technologies. The same situation with GitHub flow.

I am going to research about LinkedIn and Apple. They also had the same blockers when I created this library. Maybe at least one of them are available at the moment.

See https://twittercommunity.com/t/will-twitter-api-support-cors-headers-soon/28276/7
